# Generated by Django 5.1.7 on 2025-03-20 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ISBN', models.CharField(max_length=15)),
                ('title', models.CharField(max_length=255)),
                ('year_of_publication', models.IntegerField()),
                ('publisher', models.CharField(max_length=255)),
                ('image_url_small', models.URLField()),
                ('image_url_medium', models.URLField()),
                ('image_url_large', models.URLField()),
            ],
        ),
    ]
