# Generated by Django 5.1.7 on 2025-03-20 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_keeper', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='image_url_large',
            new_name='image_url_lg',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='image_url_medium',
            new_name='image_url_md',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='image_url_small',
            new_name='image_url_sm',
        ),
    ]
