# Generated by Django 5.1.7 on 2025-03-20 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_keeper', '0003_book_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='slug',
        ),
    ]
