# Generated by Django 5.1.7 on 2025-03-20 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_keeper', '0003_book_slug'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['ISBN'], name='books_ISBN_f5e107_idx'),
        ),
        migrations.AlterModelTable(
            name='book',
            table='books',
        ),
    ]
