# Generated by Django 5.1.7 on 2025-03-20 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_keeper', '0004_remove_book_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
