# Generated by Django 5.1.7 on 2025-03-20 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_keeper', '0005_alter_book_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_author',
            field=models.CharField(default='-', max_length=255),
            preserve_default=False,
        ),
    ]
