# Generated by Django 5.1.7 on 2025-03-20 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_keeper', '0009_alter_book_year_of_publication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='image_url_lg',
        ),
        migrations.RemoveField(
            model_name='book',
            name='image_url_md',
        ),
    ]
