# Generated by Django 5.1.7 on 2025-03-20 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_keeper', '0010_remove_book_image_url_lg_remove_book_image_url_md'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image_url_sm',
            field=models.URLField(null=True),
        ),
    ]
