# Generated by Django 5.1.7 on 2025-03-20 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_keeper', '0011_alter_book_image_url_sm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image_url_sm',
            field=models.URLField(),
        ),
    ]
