# Generated by Django 5.1.7 on 2025-03-20 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_keeper', '0012_alter_book_image_url_sm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='image_url_sm',
        ),
    ]
