# Generated by Django 5.1.7 on 2025-03-20 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_keeper', '0013_remove_book_image_url_sm'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image_url_lg',
            field=models.URLField(default='-'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='image_url_md',
            field=models.URLField(default='-'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='image_url_sm',
            field=models.URLField(default='-'),
            preserve_default=False,
        ),
    ]
