# Generated by Django 5.1.7 on 2025-03-20 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_keeper', '0014_book_image_url_lg_book_image_url_md_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='year_of_publication',
            field=models.IntegerField(),
        ),
    ]
